version: '3.8'
services:
  task-tracker:
    build:
      context: .
      dockerfile: ./apps/task-tracker/Dockerfile
      target: development
    command: npm run start:debug task-tracker
    ports:
      - '3200:3200'
    volumes:
      - .:/usr/src/app
    env_file:
      - ./apps/task-tracker/.env
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:debug auth
    ports:
      - '3201:3201'
    volumes:
      - .:/usr/src/app
    env_file:
      - ./apps/auth/.env
  auth-db:
    image: postgres:13.1-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth
    volumes:
      - dbdata-auth:/var/lib/postgresql/data
  task-tracker-db:
    image: postgres:13.1-alpine
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task-tracker
    volumes:
      - dbdata-task-tracker:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper
    hostname: zookeeper
    extra_hosts:
      - "moby:127.0.0.1"
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka
    hostname: broker
    extra_hosts:
      - "moby:127.0.0.1"
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker:9092'
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  dbdata-auth:
  dbdata-task-tracker:

